#!/usr/bin/env node
/**
 * Fetch generated TypeScript types from the Supabase Management API
 * and write them to src/lib/database.types.ts.
 *
 * Required env:
 *   SUPABASE_PAT          – account-level Personal Access Token
 *   SUPABASE_PROJECT_REF  – project reference
 */
import { writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, "..", "src", "lib", "database.types.ts");

const pat = process.env.SUPABASE_PAT;
const ref = process.env.SUPABASE_PROJECT_REF;
if (!pat || !ref) {
  console.error("ERROR: SUPABASE_PAT and SUPABASE_PROJECT_REF env vars are required");
  process.exit(1);
}

const url = `https://api.supabase.com/v1/projects/${ref}/types/typescript?included_schemas=public`;
const res = await fetch(url, {
  headers: { Authorization: `Bearer ${pat}` },
});
if (!res.ok) {
  console.error(`[${res.status}] ${await res.text()}`);
  process.exit(1);
}
const json = await res.json();
const banner =
  "// =============================================================================\n" +
  "// Auto-generated by scripts/db-types.mjs\n" +
  "// Do not edit by hand — refresh with: npm run db:types\n" +
  "// =============================================================================\n\n";
await writeFile(OUT, banner + json.types, "utf8");
console.log(`Wrote ${OUT}`);
